"""add contracts and link documents

Revision ID: 13187331524e
Revises: acdaca572f30
Create Date: 2026-07-21 19:55:06.303134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13187331524e'
down_revision: Union[str, Sequence[str], None] = 'acdaca572f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='contractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('contract_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('file_path', sa.String(length=500), nullable=False))
    op.create_foreign_key(None, 'documents', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('storage_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'contract_id')
    op.drop_table('contracts')
    # ### end Alembic commands ###
